// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Bird: typeof import('./src/components/Bird.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Light: typeof import('./src/components/Light.vue')['default']
    Node: typeof import('./src/components/Node.vue')['default']
    Paper: typeof import('./src/components/Paper.vue')['default']
    Plum: typeof import('./src/components/Plum.vue')['default']
  }
}

export { }
